#!/usr/bin/env python3
import getpass
import logging
import os

import datetime
from peewee import DoesNotExist

from iselab.models import User, db_init
from iselab.utils import create_user

WELCOME_MESSAGE = """### Welcome to the IASG ISELab!!! ###
For assistance, join the #iselab channel on https://iasg.slack.com.

Enter your ISU netID to get started.
"""

logger = logging.getLogger('iasg')
logger.setLevel(logging.INFO)
fh = logging.FileHandler('iasg.log')
fh.setLevel(logging.INFO)
formatter = logging.Formatter('%(asctime)s - %(name)s - %(levelname)s - %(message)s')
fh.setFormatter(formatter)
logger.addHandler(fh)


def main():
    db_init()
    print(WELCOME_MESSAGE)
    username = input("Username: ")
    user = None
    try:
        user = User.get(netid=username)
    except DoesNotExist:
        logger.info("Username {} didn't exist, creating new user.".format(username))
        attempts = 0
        while not user:
            if attempts == 3:
                print("Sorry.")
                logger.warning("Disconnecting {} after 3 failed attempts.".format(username))
                raise SystemExit
            user = create_user(username)
            if user:
                print("Account created successfully! Please connect again with your new credentials.")
                raise SystemExit
            else:
                print("Username didn't work, try again?")
                username = input("Username: ")
                attempts += 1
    logger.info("User {} exists".format(username))
    if user.locked:
        logger.info("Locked account {} tried to login".format(username))
        print("Your account is locked! Please request help in the #iselab channel on https://iasg.slack.com.")
        raise SystemExit
    attempts = 0
    auth = False
    while not auth:
        password = getpass.getpass()
        auth = user.verify_password(password)
        attempts += 1
        if attempts == 3:
            user.locked = True
            logger.warning("Locked account {} after 3 failed attempts".format(username))
            print("Sorry, you're locked out. Please request help in the #iselab channel on https://iasg.slack.com.")
            raise SystemExit
    user.last_login = datetime.datetime.now()
    print("Welcome back, {}! Connecting you now.".format(username))
    os.system("sshpass -p '{}' ssh {}@{}".format(user.privpass, user.netid, user.host))


if __name__ == '__main__':
    try:
        main()
    except (KeyboardInterrupt, EOFError):
        print()
        print("Exiting...")
        raise SystemExit
