import re
from urllib.parse import unquote

import requests
from flask import Flask, redirect, url_for, request, flash, render_template, make_response, send_file, abort
from flask_login import LoginManager, login_required, logout_user, login_user, current_user
from itsdangerous import URLSafeTimedSerializer
from peewee import DoesNotExist

from iselab.models import User
from iselab.settings import SECRET_KEY, WETTY, PROXIES, URL, VPN_CONFIG, db, HOST
from iselab.utils import send_email, PASSWORD_RESET_EMAIL, change_password

app = Flask(__name__)
app.secret_key = SECRET_KEY
login_manager = LoginManager()
login_manager.init_app(app)
ts = URLSafeTimedSerializer(app.config["SECRET_KEY"])


@login_manager.user_loader
def user_loader(user_id):
    return User.get(netid=user_id)


@app.route("/")
def index():
    return render_template('index.html', vpn=VPN_CONFIG, URL=URL, host=HOST)


@app.route("/webshell")
@login_required
def webshell():
    return render_template('term.html', wetty=WETTY,
                           username=current_user.netid,
                           URL=URL)


@app.route("/browser")
@login_required
def browser():
    return render_template('browser.html', URL=URL)


def proxify(html, path):
    html = re.sub(r"(https?://)(.*)/", URL + r'/browse/\2', html)
    html = re.sub(r"(action=|src=|href=|content=|srcset=|url\()(\"|')(?!http)(?!mailto)(?!//)",
                  r'\1\2{}/browse/{}/'.format(URL, '/'.join(path.split('/')[:3])),
                  html)
    return html


@app.route("/browse/")
@login_required
def empty_browse():
    return '', 204


@app.route("/vpn")
def vpn():
    if VPN_CONFIG:
        return send_file(VPN_CONFIG, as_attachment=True)
    return '', 204


@app.route("/browse/<path:path>", methods=['GET', 'POST'])
@login_required
def browse(path):
    path = unquote(path)
    headers = {'User-Agent': request.headers['User-Agent']}
    if not path.startswith('http'):
        path = 'http://' + path
    if request.method == 'GET':
        r = requests.get(path,
                         proxies=PROXIES,
                         headers=headers,
                         cookies=request.cookies,
                         verify=False)
    elif request.method == 'POST':
        r = requests.post(path,
                          data=request.form.to_dict(flat=True),
                          proxies=PROXIES,
                          headers=headers,
                          cookies=request.cookies,
                          verify=False)
    response = make_response(proxify(r.text, path))
    response.headers['Content-Type'] = r.headers['Content-Type']
    return response


@app.route("/register")
def register():
    return render_template('term.html', wetty=WETTY, username='iasg', register=True, URL=URL)


@app.route("/logout")
@login_required
def logout():
    logout_user()
    return redirect(URL)


@app.route("/reset/<token>", methods=['GET', 'POST'])
def password_reset(token):
    try:
        netid = ts.loads(token, salt='reset-password', max_age=86400)
    except:
        abort(404)
    if request.method == 'POST':
        try:
            user = User.get(netid=netid)
        except DoesNotExist:
            abort(404)
        if request.form['password'] == request.form['password_again']:
            change_password(user, request.form['password'])
            flash('Password successfully changed!')
            return redirect(URL)
        else:
            flash('Passwords do not match!')
    return render_template('reset.html')


@app.route('/login', methods=['POST'])
def login():
    username = request.form['username']
    user = None
    try:
        user = User.get(netid=username)
    except DoesNotExist:
        pass
    if request.form.get('reset'):
        if user:
            token = ts.dumps(user.netid, salt='reset-password')
            send_email(user.netid + "@iastate.edu", "IASG ISELab Password Reset",
                       PASSWORD_RESET_EMAIL.format(user.netid, URL + url_for('password_reset', token=token)))
        flash('If an account exists for that Net-ID, you will receive an email with password reset instructions.')
        return redirect(URL)
    password = request.form['password']
    if user:
        if user.verify_password(password):
            login_user(user)
            return redirect(URL)
    flash('Login failed, try again.')
    return redirect(URL)


# This hook ensures that a connection is opened to handle any queries
# generated by the request.
@app.before_request
def _db_connect():
    db.connect()


# This hook ensures that the connection is closed when we've finished
# processing the request.
@app.teardown_request
def _db_close(exc):
    if not db.is_closed():
        db.close()
